# Generated by Django 5.0.6 on 2024-05-27 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EstiloMusical",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=45)),
                ("derivado", models.BooleanField()),
                ("dancante", models.BooleanField()),
                ("cultural", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="Musico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=45)),
                ("instrumento_preferido", models.CharField(max_length=45)),
                ("data_nascimento", models.DateField()),
                ("altura", models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name="Banda",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=45)),
                ("cidade_origem", models.CharField(max_length=45)),
                ("numero_albuns", models.IntegerField()),
                ("logo", models.ImageField(upload_to="imgs")),
                (
                    "estilo_musical",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="music.estilomusical",
                    ),
                ),
                ("musicos", models.ManyToManyField(to="music.musico")),
            ],
        ),
    ]
