# Generated by Django 5.0.6 on 2024-05-27 20:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("music", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="musico",
            name="genero",
            field=models.CharField(
                choices=[("M", "Masculino"), ("F", "Feminino"), ("O", "Outro")],
                default="O",
                max_length=10,
            ),
        ),
    ]
