# Generated by Django 5.0.6 on 2024-06-10 22:50

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tesouro",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nome", models.CharField(max_length=45)),
                ("quantidade", models.IntegerField()),
                ("preco", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "img_tesouro",
                    models.ImageField(upload_to="imgs", verbose_name="Imagem"),
                ),
            ],
        ),
    ]
